# Generated by Django 4.2.6 on 2023-11-26 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quera', '0005_remove_answer_downvotes_remove_answer_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quera.answer'),
        ),
    ]
